apiVersion: v1
kind: Service
metadata:
  name: {{ include "appcharts.fullname" . }}
  labels:
    {{- include "appcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appcharts.selectorLabels" . | nindent 4 }}
